package com.example.glossariobuda;

/**
 * ICU Transliterator rules for IAST → Devanāgarī conversion (Sanskrit)
 *
 * These rules follow ISO 15919 and IAST standards for accurate Sanskrit transliteration.
 * The rule ordering is critical - ICU processes rules in the order they appear.
 */
public class IastToDevanagariRules {

    /**
     * Get the complete rule set as a string for ICU Transliterator.createFromRules()
     */
    public static String getRules() {
        return RULES;
    }

    private static final String RULES = String.join("\n",
            "# ============================================================",
            "# IAST → Devanāgarī Transliteration Rules (Sanskrit)",
            "# ============================================================",
            "# Order matters! Most specific patterns must come first.",
            "# ============================================================",
            "",
            "# ============================================================",
            "# PHASE 1: Special conjuncts and clusters",
            "# These must be processed first to avoid breaking them apart",
            "# ============================================================",
            "",
            "# Special ligatures",
            "kṣṇ → क्ष्ण;",
            "kṣ → क्ष;",
            "jñ → ज्ञ;",
            "",
            "# Nasal + consonant clusters (with proper anusvara/nasal)",
            "ṅkh → ङ्ख;",
            "ṅk → ङ्क;",
            "ṅgh → ङ्घ;",
            "ṅg → ङ्ग;",
            "",
            "ñch → ञ्छ;",
            "ñc → ञ्च;",
            "ñjh → ञ्झ;",
            "ñj → ञ्ज;",
            "",
            "ṇṭh → ण्ठ;",
            "ṇṭ → ण्ट;",
            "ṇḍh → ण्ढ;",
            "ṇḍ → ण्ड;",
            "",
            "ndh → न्ध;",
            "nd → न्द;",
            "nth → न्थ;",
            "nt → न्त;",
            "",
            "mph → म्फ;",
            "mp → म्प;",
            "mbh → म्भ;",
            "mb → म्ब;",
            "",
            "# r-clusters (very common in Sanskrit)",
            "ttr → त्त्र;",
            "tr → त्र;",
            "ddr → द्द्र;",
            "dr → द्र;",
            "ghr → घ्र;",
            "gr → ग्र;",
            "khr → ख्र;",
            "kr → क्र;",
            "phr → फ्र;",
            "pr → प्र;",
            "bhr → भ्र;",
            "br → ब्र;",
            "śr → श्र;",
            "ṣr → ष्र;",
            "sr → स्र;",
            "hr → ह्र;",
            "",
            "# s-clusters",
            "str → स्त्र;",
            "sth → स्थ;",
            "st → स्त;",
            "skh → स्ख;",
            "sk → स्क;",
            "sp → स्प;",
            "sv → स्व;",
            "sm → स्म;",
            "sn → स्न;",
            "sy → स्य;",
            "",
            "# ṣ-clusters",
            "ṣṭr → ष्ट्र;",
            "ṣṭh → ष्ठ;",
            "ṣṭ → ष्ट;",
            "ṣp → ष्प;",
            "ṣṇ → ष्ण;",
            "",
            "# Other common clusters",
            "dhv → ध्व;",
            "dhy → ध्य;",
            "dhm → ध्म;",
            "dhn → ध्न;",
            "chv → छ्व;",
            "tv → त्व;",
            "ty → त्य;",
            "dv → द्व;",
            "dy → द्य;",
            "nv → न्व;",
            "ny → न्य;",
            "hn → ह्न;",
            "hm → ह्म;",
            "hṇ → ह्ण;",
            "hy → ह्य;",
            "hl → ह्ल;",
            "hv → ह्व;",
            "py → प्य;",
            "by → ब्य;",
            "my → म्य;",
            "vy → व्य;",
            "śy → श्य;",
            "ly → ल्य;",
            "",
            "# Doubled consonants (geminates)",
            "kkh → क्ख;",
            "kk → क्क;",
            "ggh → ग्घ;",
            "gg → ग्ग;",
            "cch → च्छ;",
            "cc → च्च;",
            "jjh → ज्झ;",
            "jj → ज्ज;",
            "ṭṭh → ट्ठ;",
            "ṭṭ → ट्ट;",
            "ḍḍh → ड्ढ;",
            "ḍḍ → ड्ड;",
            "tth → त्थ;",
            "tt → त्त;",
            "ddh → द्ध;",
            "dd → द्द;",
            "nnh → न्ह;",
            "nn → न्न;",
            "pph → प्फ;",
            "pp → प्प;",
            "bbh → ब्भ;",
            "bb → ब्ब;",
            "mm → म्म;",
            "yy → य्य;",
            "ll → ल्ल;",
            "vv → व्व;",
            "śś → श्श;",
            "ṣṣ → ष्ष;",
            "ss → स्स;",
            "hh → ह्;",
            "",
            "# ============================================================",
            "# PHASE 2: Aspirated consonants (digraphs before single chars)",
            "# ============================================================",
            "",
            "kh → ख्;",
            "gh → घ्;",
            "ch → छ्;",
            "jh → झ्;",
            "ṭh → ठ्;",
            "ḍh → ढ्;",
            "th → थ्;",
            "dh → ध्;",
            "ph → फ्;",
            "bh → भ्;",
            "",
            "# ============================================================",
            "# PHASE 3: Single consonants (with inherent halant)",
            "# ============================================================",
            "",
            "k → क्;",
            "g → ग्;",
            "ṅ → ङ्;",
            "c → च्;",
            "j → ज्;",
            "ñ → ञ्;",
            "ṭ → ट्;",
            "ḍ → ड्;",
            "ṇ → ण्;",
            "t → त्;",
            "d → द्;",
            "n → न्;",
            "p → प्;",
            "b → ब्;",
            "m → म्;",
            "y → य्;",
            "r → र्;",
            "l → ल्;",
            "v → व्;",
            "ś → श्;",
            "ṣ → ष्;",
            "s → स्;",
            "h → ह्;",
            "",
            "# ============================================================",
            "# PHASE 4: Vowels (standalone forms)",
            "# Will be converted to dependent forms in next phase",
            "# ============================================================",
            "",
            "# Diphthongs first",
            "ai → ऐ;",
            "au → औ;",
            "",
            "# Long vowels",
            "ā → आ;",
            "ī → ई;",
            "ū → ऊ;",
            "ṝ → ॠ;",
            "ṛ → ऋ;",
            "ḹ → ॡ;",
            "ḷ → ऌ;",
            "",
            "# Simple vowels",
            "e → ए;",
            "o → ओ;",
            "i → इ;",
            "u → उ;",
            "a → अ;",
            "",
            "# ============================================================",
            "# PHASE 5: Convert consonant+standalone vowel to consonant+matra",
            "# This is the critical phase that fixes the 'कअ' → 'क' issue",
            "# ============================================================",
            "",
            "# Remove standalone 'a' after consonant (inherent schwa)",
            "्अ → ;",
            "",
            "# Convert other standalone vowels to matras after consonants",
            "्आ → ा;",
            "्इ → ि;",
            "्ई → ी;",
            "्उ → ु;",
            "्ऊ → ू;",
            "्ऋ → ृ;",
            "्ॠ → ॄ;",
            "्ऌ → ॢ;",
            "्ॡ → ॣ;",
            "्ए → े;",
            "्ओ → ो;",
            "्ऐ → ै;",
            "्औ → ौ;",
            "",
            "# ============================================================",
            "# PHASE 6: Anusvara, Visarga, Avagraha",
            "# ============================================================",
            "",
            "ṃ → ं;",
            "ṁ → ं;",
            "ḥ → ः;",
            "\\u0027 → \\u093D;",  // Avagraha
            "",
            "# ============================================================",
            "# PHASE 7: Punctuation and numerals",
            "# ============================================================",
            "",
            "\\|\\| → ॥;",
            "\\| → ।;",
            "",
            "0 → ०;",
            "1 → १;",
            "2 → २;",
            "3 → ३;",
            "4 → ४;",
            "5 → ५;",
            "6 → ६;",
            "7 → ७;",
            "8 → ८;",
            "9 → ९;",
            "",
            "# ============================================================",
            "# PHASE 8: Cleanup - remove trailing halants at word boundaries",
            "# Sanskrit requires explicit halant at word end",
            "# (This is actually correct, so we keep the halants)",
            "# ============================================================"
    );
}